### DISCUSSION TITLE
table of content do not show up as expected

### DISCUSSION THREAD

**Discussion by a-fly-fly-bird** [nunocoracao/blowfish#1009] [General]
Hi, I just come into this wonderful Hugo theme. I followed the official document and build up my site successfully.

But when I need to switch on top, something went wrong.I've switched `article.showTableOfContents` in `params.toml` but it didn't shows up. 

I tried to fixed it up by checking the template file and the dev tools. It seems it did not render. But as you know, I am not familiar with this stuff, so could you please point out which step did I make a mistake? Thx.

![CleanShot 2023-10-16 at 14 17 14](https://github.com/nunocoracao/blowfish/assets/70647529/c72909cc-50aa-40f2-8e9c-65db836460df)

![CleanShot 2023-10-16 at 14 22 50](https://github.com/nunocoracao/blowfish/assets/70647529/010b32cd-ac64-480b-bfa3-5dea5f4a02e7)

**Comment by a-fly-fly-bird** [comment]
I‘ve found out the reason. 

It's actually showing it, but **starting from the second level** by default! The theme's markup.toml are as below:
```toml
# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
```
Unfortunately, all of my titles are at the first level. Hugo official document has introduce this clearly: [mark up/table-of-contents](https://gohugo.io/getting-started/configuration-markup/#table-of-contents). 

So change the startLevel from 2 to 1 is just fine. 

Meanwhile, thx for help by https://github.com/olOwOlo/hugo-theme-even/issues/240#issuecomment-613780708.
