### DISCUSSION TITLE
CodeCopy & Syntax highlighting don't work for me.

### DISCUSSION THREAD

**Discussion by GrassBlock1** [nunocoracao/blowfish#1232] [Q&A] [answered]
Like issue #610 ,the copy button near code blocks and syntax highlighting don't show at all,but I had write the code block with language declaration and it seemed not work either.(even with the sample in example site)

My code block:
![图片](https://github.com/nunocoracao/blowfish/assets/46253950/54db859e-14b4-4f17-868e-0a8fb32807a1)

Render result:
![图片](https://github.com/nunocoracao/blowfish/assets/46253950/d3b3b77f-39c4-45a6-9987-f729bf3df44d)

My config:
params.toml
```toml
colorScheme = "noir"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
```

markup.toml
```toml
# -- Markup --
# These settings are required for the theme to function.

[goldmark]
    [goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
```

Regardless if its draft page or not, hugo server or generated public pages, it doesn't work.
More info can be provided if needed.
