### DISCUSSION TITLE
Can't set lang to zh-TW

### DISCUSSION THREAD

**Discussion by xlionjuan** [nunocoracao/blowfish#1371] [Q&A] [answered]
I can't set my language to zh-tw, I have tried `tw`, `TW`, `zh-tw`, `zh-TW`, `ZH-TW` .etc...multiple times....
This cause "More posts" button on home page blank, and  article's metadata gone
Can someone help me to check the file naming and my config all correct? Thank you

> hugo.toml
```toml
defaultContentLanguage = "tw"
languageCode = 'zh-tw'
```

> languages.tw.toml
```toml
languageCode = "tw"
languageName = "繁體中文"
weight = 1
title = "My website"

[params]
  displayName = "TW"
  isoCode = "zh"
  rtl = false
  dateFormat = "2 January 2006"
```

> menus.tw.toml

No language related setting
