### DISCUSSION TITLE
I integrated Blowfish with DecapCMS using Cloudflare functions + Github

### DISCUSSION THREAD

**Discussion by ibercovich** [nunocoracao/blowfish#1424] [Show and tell]
admin/ config.yml

```yml
backend:
  name: github 
  repo: me/my_repo
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://mysite.com/
  auth_endpoint: /api/auth
media_folder: static/img
# in case the public route is different, otherwise automatic
public_folder: /img
collections:
  ########################
  # POSTS COLLECTION
  ########################
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    path: "{{year}}-{{month}}-{{day}}-{{title}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    slug: "index"
    # Nested can be used for deeper than 2 layers of folders
    # nested:
    #   depth: 100 # max depth to show in the collection tree
    # summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: false
    fields:
      # - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      # - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Authors",
          name: "authors",
          widget: "select",
          multiple: true,
          options: ["bob", "jane", "peter", "kate"],
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
```

admin/ index.html

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/decap-cms@3.1.8/dist/cms.min.css">
    <title>Content Manager</title>
</head>

<body>
    <!-- Include the script that builds the page and powers Decap CMS -->
    <script src="https://cdn.jsdelivr.net/npm/decap-cms@3.1.8/dist/decap-cms.min.js"></script>
</body>

</html>
```

[Decap CMS](https://decapcms.org/)

[Oauth API to run Decap CMS on Cloudflare Pages](https://github.com/SubhenduX/decap-cms-cloudflare-pages/)
