### DISCUSSION TITLE
Why i can't see my table of contents in my article

### DISCUSSION THREAD

**Discussion by wilonweb** [nunocoracao/blowfish#1437] [Q&A]
Hello, I'm trying to display a table of contents in my article, but I can't seem to get it to work.

In `config/_default/params.toml`, I have:

```
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
```

and

```
article.showTableOfContents = true
list.showTableOfContents = true
taxonomy.showTableOfContents = true
term.showTableOfContents = true
```

Here's my article `content/my-awesome-article/index.md`:

```
---
title: "Mon Super Article Wilou"
description: "This is a demo of adding content to the homepage."
date: 2021-03-17
categories: ["blog", "tuto"]
showHero: true
draft: false
cascade:
  showDate: false
  showAuthor: false
  invertPagination: true
  hideFeatureImage: true
---

## Bonjour sous titre h2

This is a test

### sous titre h3

This is some text

#### sous titre h4

Here as well
```

My question is, why is the table of contents not displaying on my article?
