### DISCUSSION TITLE
FontAwesome icon on menu

### DISCUSSION THREAD

**Discussion by luiscachog** [nunocoracao/blowfish#1507] [General]
Hi,

I want to add a FontAwesome icon on the main menu.

I've tried to use the shortcut, but is not working, is not returning an error, but doesn't show the icon.

```toml
[[main]]
  name = "Fantasy"
  pre = '{{< icon "football" >}}'
  pageRef = "fantasy-fooball"
  identifier = "G1j2EA6a55"
  weight = 10
```

Furthermore, I've also already tried to use the HTML from FontAwesome, and also is not returning any error, but the icon is not showing.

```toml
[[main]]
  name = "Fantasy"
  pre = '<i class="fa-solid fa-football"></i>'
  pageRef = "fantasy-fooball"
  identifier = "G1j2EA6a55"
  weight = 10

```

Can you point me on how to use a FontAwesome icon on the main menu?

Thanks!
