### DISCUSSION TITLE
How to Display the Description on the Homepage

### DISCUSSION THREAD

**Discussion by wilonweb** [nunocoracao/blowfish#1525] [Q&A] [answered]
Hello,

I am trying to display the description on the homepage, but it is not working.

In `config/_default/languages.en.toml`, the title "WilOnWeb" is being recognized, but not the "description" = 'My awesome website'.

Here is the code:

```toml
languageCode = "en"
languageName = "English"
weight = 1
title = "WilOnWeb"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
```
And here my project 
https://github.com/wilonweb/blowfish.git
