### DISCUSSION TITLE
Change the font to a serif font ?

### DISCUSSION THREAD

**Discussion by manjunaths** [nunocoracao/blowfish#1712] [General]
I want to change the default font to a serif font and the article body to be serif. Is this possible ? I added a custom.css as given in the documentation and nothing changes. I think I need to change this somewhere in the tailwind configuration perhaps ? How do I do this ?

**Comment by manjunaths** [comment]
Bump! Sorry for being insistent.

Any answers to this question ? 

I want to use the [source serif font](https://fonts.google.com/specimen/Source+Serif+4?subset=devanagari&script=Deva) and unfortunately whatever is said in the documentation of on the forums are not working for me. 

Thanks in advance.

**Comment by RenaudDenis** [comment]
Here is how I did it, and it works well:

```css
@font-face {
    font-family: 'YourFont';
    font-style: normal;
    font-weight: 400;
    src: url('/fonts/YourFont.ttf');
}

@font-face {
    font-family: 'YourFont';
    font-style: italic;
    font-weight: 700;
    src: url('/fonts/YourFont-BoldItalic.ttf');
}

/* 
  Change the url according to the file names.
  Add as many font face tags as you have font files, adapting the variants in font-style and font-weight 
*/

html {
    font-family: 'YourFont', sans-serif;
}
```
