### DISCUSSION TITLE
How to enable uni-lingual site

### DISCUSSION THREAD

**Discussion by louis-vgn** [nunocoracao/blowfish#2223] [Q&A] [answered]
I cannot figure out how to remove the language toggle when the `defaultLanguageContent` parameter. When it is set, some pages do not have the parameter, but some do have it, like the homepage and the taxonomies pages.

The minimal config.toml I have with this bug is the following:

```toml
baseURL = 'localhost'
title = 'Test'
defaultContentLanguage = "fr"

[[module.imports]]
  path = "github.com/nunocoracao/blowfish/v2"
  disable = false
  
[taxonomies]
  tag = "tags"
  category = "categories"
```

And here is my structure:
```
├── content
│   ├── articles
│   │   ├── article1
│   │   └── _index.md
│   └── _index.md
├── go.mod
├── go.sum
├── hugo.toml
```

Here is the homepage:
![image](https://github.com/user-attachments/assets/161915e9-b960-4f8a-8d6b-34ccecfda72a)
There **is the language toggle**. Same thing for all taxonomy pages.

Here is an article page:
![image](https://github.com/user-attachments/assets/bd45478e-51db-4012-a291-5978a50addfa)
There is **no language toggle**.

What am I doing wrong?

**Comment by ZhenShuo2021** [comment, marked as answer]
The `languages` section is missing in your configuration. The [defaultContentLanguage](https://gohugo.io/configuration/languages/#defaultcontentlanguage) must match one of the defined [language keys](https://gohugo.io/configuration/languages/#language-keys).

Your `hugo.toml` should be like this:

```toml
title = 'My New Hugo Site'
baseURL = 'https://example.org/'
defaultContentLanguage = 'fr'

[[module.imports]]
  path = "github.com/nunocoracao/blowfish/v2"
  disable = false
  
[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.fr]
    weight = 1
    languageCode = 'fr'
    languageName = 'Français'
```
