### DISCUSSION TITLE
Issue with colorScheme on deployed to Github Pages.

### DISCUSSION THREAD

**Discussion by SupaSonic007** [nunocoracao/blowfish#592] [Q&A] [answered]
Hey, so I've got a small issue with a local vs deployed version of the site in regards to the colorScheme. Locally the colorScheme takes effect, but once deployed it defaults back to the blowfish colorScheme. I've got no extensions affecting it or anything and was wondering if you have any idea why it would not take effect?

I've got it in params.toml:
```toml
colorScheme = "Neon"
defaultAppearance = "dark"
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "img/background.png"

..
```
but it won't show up on being deployed. Any ideas?
