### DISCUSSION TITLE
Background image top chopped off

### DISCUSSION THREAD

**Discussion by manchuwook** [nunocoracao/blowfish#844] [Q&A] [answered]
Hello!
  My [site](https://9c1126c3.corp-site-f3f.pages.dev/) has the page layout and it chops off the top of the image.  I've tried adding custom.css and set `body` `background-image: top;` and it doesn't seem to have any effect.  What would I be missing?

**Comment by nunocoracao** [comment, marked as answer]
Hello @manchuwook right solution wrong css param

Override the following class
```css
.single_hero_background {
  background-repeat:no-repeat;
  background-size:cover; 
  background-position:center;
  width: calc(100% + 40px);
  z-index: -10;
  margin-left: -20px;
}
```

and change the background-position to top
