### DISCUSSION TITLE
How to zoom and pan of author image

### DISCUSSION THREAD

**Discussion by jamesbraza** [nunocoracao/blowfish#859] [Q&A]
I have an author JPG image of size 2407 x 2407:

```toml
# languages.en.toml

[author]
image = "img/photo.jpg"
```

The original image is not quite centered properly, and I was hoping to control this via a config file (my face shows just off center in the author picture).  How can I control the zoom and pan of the author image?

I was reading [Changing image optimization settings](https://blowfish.page/docs/advanced-customisation/#change-image-optimization-settings), but couldn't figure it out

Also, https://github.com/jpanther/congo/issues/526 is seemingly related

**Comment by jamesbraza** [comment]
From [this comment](https://github.com/nunocoracao/blowfish/issues/336#issuecomment-1365705699), to center my image, I needed to have:

```toml
# hugo.toml

[imaging]
# SEE: https://github.com/nunocoracao/blowfish/issues/336#issuecomment-1365705699
anchor = "Center"
```

Would still be interested in hearing how to zoom and pan manually, though
