### DISCUSSION TITLE
Example of `showDateUpdated: true` in frontmatter?

### DISCUSSION THREAD

**Discussion by jamesbraza** [nunocoracao/blowfish#866] [Q&A] [answered]
Is there an example of `showDateUpdated: true` in frontmatter somewhere?

I am turning it on, but don't see anything changing, so I am not sure what to expect.

FYI, my `dateFormat = "2006-01"` in `languages.en.toml`.

**Comment by aakashnand** [comment]
@jamesbraza did you find the answer for this?

**Reply by jamesbraza** [reply]
No I did not sadly. Looks like the example site has it like so:

```toml
# config/_default/params.toml

[article]
showDateUpdated = false
```

Can you check if it changes anything for you? It may be worth making a formal bug report for this
