### DISCUSSION TITLE
How to use a different set of images for Recent Items cards depending on dark or light mode

### DISCUSSION THREAD

**Discussion by chrisammon3000** [nunocoracao/blowfish#875] [Q&A]
When toggling between dark & light mode, is there a way that I can also change the images that are rendered inside cards for posts? I would like to use a different set of images for each mode. I am using the Blowfish theme with this configuration:
```toml
[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
```

I would like to use a different set of images for the cards shown as RecentItems, one set for when dark mode is active and the other for when light mode is active.
