### ISSUE TITLE
Impossible to overwrite image

### ISSUE THREAD

**Issue by shibumi** [nunocoracao/blowfish#130]
**Describe the bug**
It is impossible to set a custom image in config/_default/languages.en.toml.
Error message:

```
Error: failed to unmarshl config for path "/home/chris/sremuc/config/_default/languages.en.toml": "_
stream.toml:1:1": unmarshal failed: toml: key image is already defined
```

**To Reproduce**

`languages.en.toml` file:
```toml
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false
title = "SRE MUC"
description = "SRE Meetup Munich"
dateFormat = "2 January 2006"
[author]
  name = "SRE Meetup Munich"
  image = "img/blowfish_logo.png"
  headline = "'bassd scho' is not a strategy"
  image = 'bassd_scho_circle.png'
  bio = ""
  links = [
    { link = "https://www.meetup.com/de-DE/sremuc/" },
    { github = "https://github.com/dastergon/sremuc" },
    { linkedin = "https://www.linkedin.com/company/site-reliability-engineering-meetup-munich/" },
  ]
```

1. Import blowfish theme as submodule
2. Create assets/img directory: `mkdir -p assets/img`
3. place image into directory assets/img
4. link to it in the toml file

**Expected behavior**
It should be possible to overwrite 

**Hugo & Blowfish versions**
* Hugo v0.104.3
* Blowfish imported as submodule: ` d8eee1c5ed9e5befa482e8caf0f2fe3525473ac3 ../../themes/blowfish (v2.0.1)`
