### ISSUE TITLE
Nested menu loses link targets

### ISSUE THREAD

**Issue by Taffer** [nunocoracao/blowfish#1342]
**Describe the bug**

Two our of the four items in my nested menu have empty `href=""` in the generated HTML source, and I can't figure out how or why, or how to fix it.

**To Reproduce**

I've added a "Games" heading to my site's main menu, with four entries beneath it; the idea is for a click on "Games" to go to a page about games, and each entry to go to a specific game's page. On-disk, the layout is like this:

```
content/games/_index.md
content/games/skelly/index.md
content/games/arcana/index.md
content/games/schrodingers-chicken/index.md
content/games/book-of-the-dead/index.md
```

and I've got this in my `menus.en.toml`:

```toml
[[main]]
  name = "Games"
  pageRef = "games"
  weight = 40
  pre = "ghost"

[[main]]
  parent = "Games"
  name = "Arcana"
  pageRef = "arcana"
  weight = 40
  pre = "globe"

[[main]]
  parent = "Games"
  name = "Schrödinger’s Chicken"
  pageRef = "schrodingers-chicken"
  weight = 40
  pre = "bomb"

[[main]]
  parent = "Games"
  name = "Skelly"
  pageRef = "skelly"
  weight = 40
  pre = "globe"

[[main]]
  parent = "Games"
  name = "Untitled Egyptian-Themed Game"
  pageRef = "book-of-the-dead"
  weight = 40
  pre = "globe"
```

In the generated site, the links to "Arcana" and "Skelly" are empty, literally `<a href=""`.

**Expected behavior**

I expected to get a "Games" item in my main menu, with sub-menu items going to the four game-specific pages.

**Screenshots**

You can see it in action here: https://taffer.ca/

Source is here: https://codeberg.org/Taffer/taffer.ca

**Desktop (please complete the following information):**

 - OS: Kubuntu Linux 23.10
 - Browser: Firefox 123.0.1

**Hugo & Blowfish versions**

```sh
chrish@perceptor$ hugo version
hugo v0.113.0+extended linux/amd64 BuildDate=2024-01-23T04:15:35Z VendorInfo=ubuntu:0.113.0-3ubuntu0.1
```

and the Blowfish version is:

```
commit 65956f10b96b43350cf387f5d45c0cabe759e0cb (HEAD -> main, tag: v2.61.1, origin/main, origin/HEAD)
Merge: 6c6a5591 35ab2596
Author: Nuno Coração <nunocoracao@gmail.com>
Date:   Tue Mar 12 19:09:51 2024 +0000

    Merge pull request #1317 from nunocoracao/dev
    
    🔖 v2.61.1
```
