### ISSUE TITLE
✏️ Getting Started docs refer to nonexistant file(s?)

### ISSUE THREAD

**Issue by nk9** [nunocoracao/blowfish#1514]
**Describe the bug**
The [Getting Started page](https://blowfish.page/docs/getting-started/) starts out describing a `config.toml` file with various settings. It's supposedly at `config/_default/config.toml`. However, this path doesn't exist in a fresh project created with `blowfish-tools`. The path now appears to be `config/_default/hugo.toml`.

<img width="686" alt="image" src="https://github.com/nunocoracao/blowfish/assets/3646730/a4dea4aa-bf7a-4164-b416-2ad0e798dff1">

<img width="759" alt="image" src="https://github.com/nunocoracao/blowfish/assets/3646730/cc520f67-a36a-4536-b9ce-56af75c38f1d">

There is also a `./hugo.toml` file, though, which is the one that actually seems to contain the settings for `baseURL`, `languageCode`, and `title`. Is this the file that's actually being referred to? Or is the user supposed to create a new file at the given path in `_default`?

**To Reproduce**
1. Create a new blog with `blowfish-tools new my_blog`
2. Look in `my_blog/config/_default`
3. Notice missing `config.toml` file.

**Expected behavior**
Docs should describe the current version.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5

**Hugo & Blowfish versions**
Blowfish 2.69.0
Hugo 0.126.3+extended darwin/arm64

**Comment by nk9** [comment]
Thanks for the quick work on this!

I was wondering, though: there's still the confusion between `config/_default/hugo.toml` and the `hugo.toml` in the root directory. The file pointed to by the path on `index.it.md` line 32 doesn't have a `languageCode`, and the `baseURL` is commented out.

```toml
# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
```

Is the path on line 32 actually correct? If so, then the TOML code starting on line 31 is misleading.
