### ISSUE TITLE
showMoreLink not correctly working with languages

### ISSUE THREAD

**Issue by Thanatermesis** [nunocoracao/blowfish#1568]
My website default language points to /, there's a spanish version of it pointing to /es

So I have /posts and /es/posts  to list posts

In the Spanish version, when I click in the "Show More" button of the homepage, it redirects to the english version in /posts instead of its sub-url /es, so /es/posts

IMHO this setting should be correctly detected, on the other hand I tried to add the setting in languages.es.toml as:

```
[homepage]
  showMoreLink = true
  showMoreLinkDest = "/es/posts"
```

But it failed showing a homepage without contents instead

**Comment by knowinginner** [comment]
You need to have /content/_index.md, _index.es.md 
Cheers :-)

**Comment by Thanatermesis** [comment]
Hum... I just checked them in the examplesite files, I don't think it has relation with the showMore button issue? 🤔

**Comment by nunocoracao** [comment]
@Thanatermesis this use-case is enabled on the Blowfish website, and it works corretly. Check the exampleSite folder in this repo for more details. 

Having said this, the way this logic is setup is done in Hugo not Blowfish, I would check their documentation for extra help with the configuration.

**Comment by Thanatermesis** [comment]
I have been trying to add the setting in multiple places without success, which is the exact file I need to add it and how? it is not in /config/_default/ ?

@nunocoracao why not set the defaults to what is already configured? for example in my case, from these settings:

languages.es.toml --> languageCode = "es", and then menus.es.toml --> pageRef = "/posts", then the showMore link should point to "/es/posts"

**Comment by nunocoracao** [comment]
How are you structuring the different languages?

**Comment by Thanatermesis** [comment]
hugo.toml:

    defaultContentLanguage = "en"

languages.en.toml:

    languageCode = "en"
    languageName = "English"
    weight = 1

    [params]
    displayName = "EN"
    isoCode = "en"

languages.es.toml:
   
    languageCode = "es"
    languageName = "Spanish"
    weight = 2

    [params]
    displayName = "ES"
    isoCode = "es"

menus.en.toml:

    [[main]]
    name = "Posts"
    pageRef = "posts"
    weight = 10

    [[main]]
    name = "Topics"
    pageRef = "categories"
    weight = 20

    [[footer]]
    name = "Tags"
    pageRef = "tags"
    weight = 10

    [[footer]]
    name = "Topics"
    pageRef = "categories"
    weight = 20


menus.es.toml:

    [[main]]
    name = "Publicaciones"
    pageRef = "posts"
    weight = 10

    [[main]]
    name = "Temas"
    pageRef = "categories"
    weight = 20

    [[footer]]
    name = "Etiquetas"
    pageRef = "tags"
    weight = 10

    [[footer]]
    name = "Temas"
    pageRef = "categories"
    weight = 20

params.toml:

```toml
# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.jage/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

disableImageZoom = false
disableImageOptimization = false

disableTextInHeader = false

defaultBackgroundImage = "background-site.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-gradient" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  # showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateOnlyInArticle = true
  showDateUpdated = true
  showAuthor = true
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/Thanatermesis/blog/"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = true
  showComments = true
  # sharingLinks = [ "linkedin", "twitter", "reddit", "email"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

```
