### ISSUE TITLE
enableCodeCopy does not work when codeFences is set to false

### ISSUE THREAD

**Issue by eallion** [nunocoracao/blowfish#1691]
`enableCodeCopy` does not work when `codeFences` is set to `false`

- params.toml

```toml
enableCodeCopy = true
```

- markup.toml

```toml
[highlight]
  codeFences = false
```
