### ISSUE TITLE
Nested menu items are not readable

### ISSUE THREAD

**Issue by schneekluth** [nunocoracao/blowfish#1790]
**Describe the bug**
When using nested menus items are not readable.

**To Reproduce**

1. Create a nested menu item:
    ```toml
    [[main]]
      name = "tax"
      weight = 40

    [[main]]
      name = "Categories"
      parent = "tax"
      url = "/categories"
      weight = 43
    ```
2. Launch preview server
3. Hover over nested parent.

**Expected behavior**
A readable list of nested menu items.

**Screenshots**
![nested-menu-issue](https://github.com/user-attachments/assets/00b8bfea-34f2-4441-9cb7-5ac056fc1226)
nshots**

![nested-menu-issue](https://github.com/user-attachments/assets/601a9685-03d5-4bab-ab3e-f510ed2b28c0)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11, OSX 15}
 - Browser: Chrome (129), Firefox (131)

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
+ Hugo: `135.0`
+ Blowfish: `2.78.0`

**Additional Info**
Example screenshot uses default theme `blowfish` but can also be reproduced with `noir` theme.
