### ISSUE TITLE
Footer not .active

### ISSUE THREAD

**Issue by adilhyz** [nunocoracao/blowfish#1943]
Something needs to be fixed

![Image](https://github.com/user-attachments/assets/31311826-a60e-4d58-aa9d-5ab6bcdc5ea0)

## issue
when in the navbar it works hover but in my case not with the footer
> * hugo: 0.140.2
> * blowfish: v2.81.0

**Comment by hudsonm62** [comment]
can you send what you're using for menus config?

**Comment by adilhyz** [comment]
> can you send what you're using for menus config?

yeah i use this

<details>
<summary><b>Screenshot</b></summary>

![Image](https://github.com/user-attachments/assets/86c683fa-8b75-466c-a1bb-1e4a3fd48bdf)
</details>

``` toml

[[subnavigation]]
  name = "Tags"
  pre = "tag"
  pageRef = "tags"
  weight = 14

[[subnavigation]]
  name = "Categories"
  pre = "list"
  pageRef = "categories"
  weight = 15

[[footer]]
 name = "Tags"
 pre = "tag"
 pageRef = "tags"
 weight = 15

[[footer]]
 name = "Categories"
 pre = "list"
 pageRef = "categories"
 weight = 20
```

`explanation` : sub navigation is a display where there is a hover because it's in the menu, while the footer is not.
