### ISSUE TITLE
JavaScript/CSS Background Animation

### ISSUE THREAD

**Issue by Chill-Try** [nunocoracao/blowfish#1953]
**Describe the solution you'd like**
homepageImage but `.js` file
```toml
# params.toml
[homepage]
  layout = "background"
  homepageImage = "background/particles/particles.js"
```

**Describe alternatives you've considered**
```toml
# params.toml
[homepage]
  layout = "custom"
```

**Additional context**
Can I choose javascript file as background without creating `layouts/partials/home/custom.html`?

--- ---
\# assets/background/particles
![Image](https://github.com/user-attachments/assets/94783706-daca-4a74-9aee-e6677f901760)

--- ---
Sorry, this may be a bit stupid, I am a front-end noob
