### ISSUE TITLE
`pre` block scrollbar not customized properly

### ISSUE THREAD

**Issue by ZhenShuo2021** [nunocoracao/blowfish#1967]
**Describe the bug**  
The scrollbar in the `pre` block is not customized and uses the default browser scrollbar.

**Expected behavior**  
It should be controlled by `-webkit-scrollbar`.

**Hugo & Blowfish versions**  
Both are up-to-date: Hugo v0.143.1, Blowfish v2.82.0

**Comment by ZhenShuo2021** [comment]
Test with Tailwind CSS:

```css
@utility scrollbar-custom {
  &::-webkit-scrollbar {
    width: 10px;
    height: 10px;
  }
  
  &::-webkit-scrollbar-track {
    @apply bg-neutral-200 rounded-2xl dark:bg-neutral-800;
  }
  
  &::-webkit-scrollbar-thumb {
    @apply bg-neutral-500 rounded-lg;
  }
  
  &::-webkit-scrollbar-thumb:hover {
    @apply bg-neutral-600 dark:bg-neutral-500;
  }
}

pre {
  text-align: left;
  @apply scrollbar-custom;
}
```

not good, close.
