### ISSUE TITLE
✨Background improvements

### ISSUE THREAD

**Issue by madoke** [nunocoracao/blowfish#245]
Configuring the background image feels a little bit weird because the concepts of background and cover/hero are treated equally in the current implementation:

```yaml
article:
  showHero: true
  heroStyle: background
```

Which makes it impossible to have a hero image on top of a background image.

Another issue is that setting up a background image for the homepage is different from the rest, making it a bit confusing for the user:

```yaml
homepage:
  homepageImage: 'img/something.png'
  layout: background
```

I'd like to propose changing the configuration/implementation to split the concepts of hero and background, while using the same configuration style across all layouts. Example configuration:

```yaml
# params.yml
---
backgroundImage: img/jungle.png

article:
  backgroundImage: img/lion.png

list:
  # defaults to Site.Params.backgroundImage

homepage:
  backgroundImage: img/monkeys.png
```

Using the above strategy, all layouts would display a background image if the property `<layout>.backgroundImage` is defined, or fallback to the global `backgroundImage` at the root of the params file. If none is defined, the default theme background is used.

The benefits for this approach would naturally be coherent configuration options and the possibility of displaying hero/cover images on top of any background

I'm happy to contribute with a pull request should this proposal be accepted
