### ISSUE TITLE
:lipstick: Exclude "code" tag from Tailwind config

### ISSUE THREAD

**Issue by fredrikaverpil** [nunocoracao/blowfish#372]
### Problem description

When writing inline code in markdown, using single backticks, the rendered text does not look like what you would expect.

### Current behavior

When writing the following markdown:

```
This blog post is heavily influenced by her approach of setting up the `app` and `app86` versions for apps which might need both native and emulated treatment.
```

This gets rendered:

![image](https://user-images.githubusercontent.com/994357/210141464-755edaeb-ba7b-4074-9213-4e3b73a95a6f.png)

### Desired/expected behavior:

Instead, the desired rendering would be something like this:

![image](https://user-images.githubusercontent.com/994357/210141475-fc94d7c1-f8f5-4d3c-96df-c9379c5cd2d1.png)

Meaning no backticks, use same font and background color as for code blocks.

### What needs to be done

Currently, the Tailwind-generated CSS includes some undesired code (in `main.css`):

```css
.prose :where(code):not(:where([class~="not-prose"] *)) {
  color: var(--tw-prose-code);
  font-weight: 600;
  font-size: 0.875em;
}

.prose :where(code):not(:where([class~="not-prose"] *))::before {
  content: "`";
}

.prose :where(code):not(:where([class~="not-prose"] *))::after {
  content: "`";
}
```

I believe that `tailwind.config.js` needs to be updated with something like what is discussed [here](https://github.com/tailwindlabs/tailwindcss-typography/issues/32) or outlined [here](https://www.hood-smith.me.uk/posts/custom-theme-with-tailwindcss/).

**Comment by fredrikaverpil** [comment]
I might add that this is my current workaround:

```css
/* custom.css */

/* Override blowfish's main.css: tweak code tags */
.prose :where(code):not(:where([class~="not-prose"] *)) {
  background-color: var(--tw-prose-pre-bg);
  color: var(--tw-code);
  border-radius: 0.375rem;
}

/* Override blowfish's main.css: Ugly fix to remove backticks */
.prose :where(code):not(:where([class~="not-prose"] *))::before {
  content: "";
}

/* Override blowfish's main.css: Ugly fix to remove backticks */
.prose :where(code):not(:where([class~="not-prose"] *))::after {
  content: "";
}

```
