### ISSUE TITLE
KaTeX wouldn't render multiline math formulas in multilines

### ISSUE THREAD

**Issue by abalajiksh** [nunocoracao/blowfish#551]
https://ashwinbalaji.xyz/posts/calculus-to-linear-algebra/

<img width="763" alt="Screenshot 2023-02-26 at 12 09 06 PM" src="https://user-images.githubusercontent.com/125642240/221407009-64681865-6314-41cd-9c5c-a02f55b9479a.png">
this is what it rendered
<img width="750" alt="Screenshot 2023-02-26 at 12 09 35 PM" src="https://user-images.githubusercontent.com/125642240/221407043-b42b2be7-d012-48a4-8978-395f404a968b.png">
this is I want it to render as.

check the above article, in the Linear Algebra section, most of the matrix elements get rendered in a single line. not just the above article, but in other articles too. I tried using mathjax directly, eliminating KaTeX but the problem seems to exist. Raising the issue here to bring attention to this problem.

**Comment by nunocoracao** [comment]
If anything this would be a latex issue not Blowfish nor Hugo. Please do check Katex docs on how to achieve that to check if there's no mistake in your code. 

https://katex.org/docs/supported.html

Otherwise, please report this in Katex repo.

**Comment by nisetynet** [comment]
abalajiksh may have already solved the problem, but I'm leaving the information here because I encountered the same problem and struggled with it.

I had to escape the `\\`([katex newline](https://katex.org/docs/supported.html#line-breaks)).

![hugo_katex](https://github.com/nunocoracao/blowfish/assets/155320335/edf9235c-cc88-40cb-921f-35767abba094)

You can also use [`\newline`](https://katex.org/docs/supported.html#line-breaks).

I found the solution in this issue.
https://github.com/KaTeX/KaTeX/issues/1831#issuecomment-453703898

**Comment by yoghurtlee-thu** [comment]
Using `\\\\` is indeed a solution, but I think it's not elegant enough. After my experiments, you can add the following configuration to the `hugo.toml` in the site's **root directory**.

```TOML
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions.passthrough]
            enable = true
            delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
            # using $ as the inline-delimiter (optional, maybe)
            delimiters.inline = [["\\(", "\\)"], ["$", "$"]]
```

I hope this can be helpful to you :)
