### ISSUE TITLE
🐛 RTL Style issue

### ISSUE THREAD

**Issue by mahmoud-000** [nunocoracao/blowfish#700]
**Header Menu Margin**

![arabic style issue](https://user-images.githubusercontent.com/25666329/235622741-d4af1b40-910d-4980-ae15-b3c150ce5132.png)

**To Fix That**
1. Go to 'assets'
2. Create folser 'css.'
3. Create file `custom.css` in folder `css`
4. Add this snippets into custom.css file

```css
.space-x-5>a {
  --tw-space-x-reverse: 0;
  margin-right: calc(1.25rem * var(--tw-space-x-reverse));
  margin-left: calc(1.25rem * calc(1 - var(--tw-space-x-reverse)));
}
```

![fixed arabic style](https://user-images.githubusercontent.com/25666329/235622746-8dce3557-2a5d-4250-80ef-8e0770788ad5.png)
