### ISSUE TITLE
 :bug: [params.title] disappeared from top navbar in v2.35.0 ?

### ISSUE THREAD

**Issue by gustaveWPM** [nunocoracao/blowfish#765]
Hello! :wave:

**Describe the bug**
Looks like the `title` value, next to the logo in the navbar ("Blowfish" in the _example site_), is not showing anymore?

**To Reproduce**
I updated my `languages.fr.toml` code from:

```toml
# * ...

title = "GustaveWPM"
description = "Découvrez mes projets et mon blog de développeur web grâce auquel je partage ma passion ! Exemples de technologies utilisées : React, TypeScript, ExpressJS, Hugo..."
languageCode = "fr"
languageName = "Français"
isoCode = "fr"
weight = 1
rtl = false

logo = "/img/wpm-logo.webp"
# copyright = "Copy, _right?_ :thinking_face:"

displayName = "FR"
dateFormat = "2 January 2006"

# * ...
```

to:
```toml
[params]
  title = "GustaveWPM"
  description = "Découvrez mes projets et mon blog de développeur web grâce auquel je partage ma passion ! Exemples de technologies utilisées : React, TypeScript, ExpressJS, Hugo..."
  languageCode = "fr"
  languageName = "Français"
  isoCode = "fr"
  weight = 1
  rtl = false

  logo = "/img/wpm-logo.webp"
  # copyright = "Copy, _right?_ :thinking_face:"

  displayName = "FR"
  dateFormat = "2 January 2006"
```

I'm using Hugo `v0.112.7`.

---

EDIT: wow, I'm really sorry.
Just writing `title` at the top of the `languages.fr.toml` file works perfectly fine and doesn't trigger any warning.

I'm just a Hugo newbie.
