### ISSUE TITLE
📹 Video size rendering issue

### ISSUE THREAD

**Issue by martinvisser** [nunocoracao/blowfish#834]
**Describe the bug**
After upgrading the theme to 2.37.0 I see some issues with rendering videos. I haven't changed anything else, just a new version of this theme. It worked fine with 2.36.1.

**Screenshots**
With version 2.36.1:
![236](https://github.com/nunocoracao/blowfish/assets/3170236/0cef28b8-ca31-47e7-92b9-714ad7e2be47)

With 2.37.0:
![237](https://github.com/nunocoracao/blowfish/assets/3170236/24ff7cdb-b9e1-4c3d-b948-ca2d1ece5070)

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
Hugo: v0.115.3
Blowfish: 2.37.0

**Comment by nunocoracao** [comment]
Will need time to investigate this one @martinvisser could you provide access to the code? or at least which layout is this referring to?
Also, is this something you can clearly go back and forth in the versions and see the difference? or might it be caused by a change in the youtube embed for example?

**Comment by martinvisser** [comment]
@nunocoracao thanks for looking into it!
When I switched back to `v2.36.1` the rendering issue was gone, so the only change I did was updating to the latest theme and back again to fix it.

The file is using the following code:
```md
---
title: "Simon's Cat in 'Cat &amp; Mouse'"
date: "2011-09-03T12:37:36"
---

{{< youtube BWIPZvwcnX8 >}}
```

And the following params:
```yaml
colorScheme: slate
defaultAppearance: dark
defaultBackgroundImage: img/background.jpg
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
mainSections:
  - posts
footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: false
header:
  layout: fixed
homepage:
  layout: background
  homepageImage: img/background.jpg
  showRecent: true
  showRecentItems: 6
  showMoreLink: true
  showMoreLinkDest: posts
  cardView: true
  cardViewScreenWidth: false
  layoutBackgroundBlur: true
article:
  showDate: true
  showViews: false
  showLikes: false
  showDateUpdated: false
  showAuthor: false
  showHero: true
  heroStyle: background
  layoutBackgroundHeaderSpace: false
  layoutBackgroundBlur: true
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: true
  showReadingTime: true
  showTableOfContents: false
  showTaxonomies: false
  showAuthorsBadges: false
  showWordCount: false
  showSummary: true
  sharingLinks:
    - linkedin
    - pinterest
    - reddit
    - facebook
    - email
list:
  showHero: true
  heroStyle: background
  layoutBackgroundHeaderSpace: false
  layoutBackgroundBlur: true
  showBreadcrumbs: false
  showSummary: true
  showTableOfContents: false
  showCards: true
  groupByYear: false
  cardView: true
  cardViewScreenWidth: false
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
fathomAnalytics: { }
verification: { }
imaging:
  anchor: Smart
  bgColor: '#1f2937'
  hint: photo
  quality: 75
  resampleFilter: box
galleryLoadJQuery: true
gallerySortOrder: asc
galleryRowHeight: 150
galleryMargins: 5
galleryThumbnailResizeOptions: "600x450 webp photo"
galleryImageResizeOptions: "1440x1080 webp photo"
galleryShowExif: false
galleryPreviewType: blur
galleryEmbedPreview: false
galleryThumbnailHoverEffect: enlarge
galleryLastRow: nojustify
```

If you need more, please let me know!
