### ISSUE TITLE
Cannot build site. Error: "<.>: range can't iterate over governance"

### ISSUE THREAD

**Issue by anoduck** [nunocoracao/blowfish#906]
**Describe the bug**
I wish I knew exactly the moment this bug became triggered, so I could understand what change caused it to occur. I had just formatted front matter for several files in order to improve crawlability. Then went to build the site and whamo, it fails with this message.

```yaml
---
title: "{{ replace .Name "-" " " | title }}"
description: ""
slug: "{{ replace .Name "-" " " | title}}"
hero: "featured.png"
tags: ["pages", "test"]
date: {{ .Date }}
draft: true
---
```

**To Reproduce**
1. Use the provided archetype template to create a post
2. build site

**Expected behavior**
I really do no know what caused the build to fail. 

**Desktop (please complete the following information):**
 - OS: Kali Linux Rolling Release
 - Browser: Google Chrome
 - Version: NA

**Hugo & Blowfish versions**
- Hugo: 0.113.0+extended
- Blowfish: Current (i.e. pulled from main)

**Additional context**
```bash
hugo v0.113.0+extended linux/amd64 BuildDate=2023-07-06T15:15:58Z VendorInfo=debian:0.113.0-2
Total in 1850 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/home/user/Site/themes/blowfish/layouts/_default/baseof.html:8:4": 
execute of template failed: template: _default/list.html:8:4: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/home/user/Site/themes/blowfish/layouts/partials/head.html:21:42": 
execute of template failed: template: partials/head.html:21:42: executing "partials/head.html" at <.>: range can't iterate over governance
```
