### ISSUE TITLE
Don't center-align code within blocks

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#957]
**Describe the bug**

Code is centered within a markdown code block on a centered page (like main page with showRecent=false) .

This might fix it:

```css
.chroma {
  text-align: left;
}
```

**Comment by nunocoracao** [comment]
I opted for 
```css
pre {
  text-align: left;
}
```

to cover the use-case where no language is defined in the block
