### ISSUE TITLE
Heading first-child styling not working

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#959]
**Describe the bug**

The anchor div in `render-heading.html` is above the heading:

```html
<div id="{{ .Anchor | safeURL }}" class="anchor"></div>
<h...
```

This bypasses :first-child styling:

```css
.prose :where(.prose > :first-child):not(:where([class~="not-prose"] *)) {
  margin-top: 0;
}
```

Which leads to an unexpectedly big gap above first-child headings (noticeable in H2 and beyond).

Moving the div inside of the `<h>` seems to fix the issue.
